image: $CI_REGISTRY_IMAGE

stages:
  - docker
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

build:docker:
  stage: docker
  image: docker:stable
  tags:
    - docker-build
  services:
    - docker:stable-dind
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    changes:
      - Dockerfile

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
  artifacts:
    paths:
      - build/nfsreplay
      - build/nfsreplay_test

unit-tests:
  dependencies:
    - build
  script:
    - cd build
    - ./nfsreplay_test -r junit -o ../test-report.xml
  artifacts:
    when: always
    paths:
      - test-report.xml
    reports:
      junit:
        - test-report.xml
